version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  authenticate:
    lang: node10-express
    handler: ./authenticate
    image: ${DOCKER_USER:-127.0.0.1:5000}/authenticate:latest
    secrets:
      - jwtRS256.key
      - password-secret
      - internal-secret
  authorize:
    lang: node10-express
    handler: ./authorize
    image: ${DOCKER_USER:-127.0.0.1:5000}/authorize:latest
    secrets:
      - jwtRS256.key.pub
