version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  unidades-de-saude:
    lang: node10-express
    handler: ./unidades-de-saude
    image: ${DOCKER_USER:-127.0.0.1:5000}/unidades-de-saude:latest
    secrets:
      - internal-secret